<Project>
  <PropertyGroup>
    <!-- Enable central package management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- Enable Transitive Package Pinning -->
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    <RoslynVersion>5.3.0</RoslynVersion>
    <!-- https://learn.microsoft.com/en-us/nuget/concepts/auditing-packages -->
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>direct</NuGetAuditMode>
    <NuGetAuditLevel>critical</NuGetAuditLevel>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="$(RoslynVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Features" Version="$(RoslynVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="$(RoslynVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="$(RoslynVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.6" />
    <PackageVersion Include="ModelContextProtocol" Version="1.2.0" />
    <PackageVersion Include="NuGet.Protocol" Version="7.3.1" />
    <PackageVersion Include="System.CommandLine" Version="2.0.6" />
    <PackageVersion Include="WeihanLi.Common" Version="1.0.88" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="GitHubActionsTestLogger" Version="3.0.3" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
    <PackageVersion Include="Xunit.DependencyInjection" Version="11.2.1" />
  </ItemGroup>
</Project>