name: default

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Running tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET SDK
      uses: WeihanLi/dotnet-install@v0.2.0
      with:
        version: |
          10.x
          11.x
    - name: dotnet info
      run: dotnet --info
    - name: build-on-windows
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        .\build.ps1 --target=test
    - name: build-on-non-windows
      if: matrix.os != 'windows-latest'
      run: bash build.sh --target=build
